### ISSUE TITLE
ERROR: LoadError: The artifact at C:\Users\name\.julia\artifacts\58bd87695e9ccdb508cb38be1ab717315ecc9152 is empty.

### ISSUE THREAD

**Issue by SchwammPizza** [JuliaGPU/CUDA.jl#1209]
```
ERROR: LoadError: The artifact at C:\Users\name\.julia\artifacts\58bd87695e9ccdb508cb38be1ab717315ecc9152 is empty.
This is probably caused by a failed download. Remove the directory and try again.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:33
  [2] cuda_artifact(id::Any, cuda::VersionNumber)
    @ CUDA.Deps ~\.julia\packages\CUDA\YpW0k\deps\bindeps.jl:99
  [3] find_cudnn(cuda::CUDA.Deps.ArtifactToolkit, version::Any)
    @ CUDA.Deps ~\.julia\packages\CUDA\YpW0k\deps\bindeps.jl:510
  [4] macro expansion
    @ ~\.julia\packages\CUDA\YpW0k\deps\bindeps.jl:500 [inlined]
  [5] macro expansion
    @ lock.jl:209 [inlined]
  [6] libcudnn(; throw_error::Bool)
    @ CUDA.Deps ~\.julia\packages\CUDA\YpW0k\deps\bindeps.jl:19
  [7] has_cudnn()
    @ CUDA.Deps ~\.julia\packages\CUDA\YpW0k\deps\bindeps.jl:507
  [8] top-level scope
    @ ~\.julia\packages\CUDA\YpW0k\test\runtests.jl:169
  [9] include(fname::String)
    @ Base.MainInclude .\client.jl:444
 [10] top-level scope
    @ none:6
in expression starting at C:\Users\name\.julia\packages\CUDA\YpW0k\test\runtests.jl:169
ERROR: Package CUDA errored during testing
```

I have testet:
```
(@v1.6) pkg>test CUDA
```

I have CUDNN, CUDA, Julia, CUDA.jl uptodate.

**Comment by maleadt** [comment]
Did you try what the error message asks you to do?

**Comment by SchwammPizza** [comment]
I don't understand wich directory, because it can't be CUDA.jl wich is meant

**Comment by maleadt** [comment]
`C:\Users\name\.julia\artifacts\58bd87695e9ccdb508cb38be1ab717315ecc9152`

**Comment by SchwammPizza** [comment]
i deleted it but it got recreated after the next turn

**Comment by maleadt** [comment]
Yes, that's expected. Did it have any contents, and did you get past the error?

**Comment by SchwammPizza** [comment]
I have tried it again, I had deleted it wrongly the first time. Now it works, but I get a new error:

```
Error in testset array:
Error During Test at none:1
  Got exception outside of a @test
  ProcessExitedException(6)
Error in testset cudadrv:
Error During Test at none:1
  Got exception outside of a @test
  ProcessExitedException(8)
Error in testset cublas:
Error During Test at none:1
  Got exception outside of a @test
  ProcessExitedException(4)
Error in testset cusparse:
Error During Test at none:1
  Got exception outside of a @test
  ProcessExitedException(16)
Error in testset random:
Error During Test at none:1
  Got exception outside of a @test
  ProcessExitedException(13)
Error in testset cusolver\sparse:
Error During Test at none:1
  Got exception outside of a @test
  ProcessExitedException(2)
Error in testset cusolver\dense:
Error During Test at none:1
  Got exception outside of a @test
  ProcessExitedException(7)
ERROR: LoadError: Test run finished with errors
in expression starting at C:\Users\name\.julia\packages\CUDA\YpW0k\test\runtests.jl:573
ERROR: Package CUDA errored during testing
```

**Comment by maleadt** [comment]
These are unrelated. You also didn't include the actual stack trace/error.

Please put some more effort in the issues you file: Formatting (use triple backticks), ensuring all information is there (you didn't follow the issue template asking for crucial information like the Julia version, CUDA.jl version, platform, etc).
