### ISSUE TITLE
"initialization" test failing

### ISSUE THREAD

**Issue by RonRahaman** [JuliaGPU/CUDA.jl#1435]
I'm running the tests for CUDA.jl (with `]test CUDA`) and the "initialization" test is failing.  All the other tests are passing.  I first mentioned this on [Discourse](https://discourse.julialang.org/t/cuda-jl-initialization-test-failing/77526), and @maleadt asked me to report it.  

Here is the error message:
```
Error in testset initialization:
Test Failed at /usr/local/pace-apps/manual/packages/julia/1.7.2/gcc-8.3.0/pace/packages/CUDA/Axzxe/test/initialization.jl:98
  Expression: CUDA.math_precision() != :Float16
   Evaluated: Float16 != Float16
ERROR: LoadError: Test run finished with errors
in expression starting at /usr/local/pace-apps/manual/packages/julia/1.7.2/gcc-8.3.0/pace/packages/CUDA/Axzxe/test/runtests.jl:550
ERROR: Package CUDA errored during testing
```

And here is my system info.  Thanks!
```
julia> CUDA.versioninfo()
  Downloaded artifact: CUDA_compat
  Downloaded artifact: CUDA
CUDA toolkit 11.6, artifact installation
NVIDIA driver 495.29.5, for CUDA 11.5
CUDA driver 11.5

Libraries:
- CUBLAS: 11.8.1
- CURAND: 10.2.9
- CUFFT: 10.7.0
- CUSOLVER: 11.3.2
- CUSPARSE: 11.7.1
- CUPTI: 16.0.0
- NVML: 11.0.0+495.29.5
  Downloaded artifact: CUDNN
- CUDNN: 8.30.2 (for CUDA 11.5.0)
  Downloaded artifact: CUTENSOR
- CUTENSOR: 1.4.0 (for CUDA 11.5.0)

Toolchain:
- Julia: 1.7.2
- LLVM: 12.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

4 devices:
  0: Quadro RTX 6000 (sm_75, 23.650 GiB / 23.653 GiB available)
  1: Quadro RTX 6000 (sm_75, 23.650 GiB / 23.653 GiB available)
  2: Quadro RTX 6000 (sm_75, 23.650 GiB / 23.653 GiB available)
  3: Quadro RTX 6000 (sm_75, 23.650 GiB / 23.653 GiB available)
```

**Comment by Marpell** [comment]
**Same** initialization test failure for me, here's the info:

julia> CUDA.versioninfo()
CUDA toolkit 11.6, artifact installation
NVIDIA driver 470.74.0, for CUDA 11.4
CUDA driver 11.6

Libraries: 
- CUBLAS: 11.8.1
- CURAND: 10.2.9
- CUFFT: 10.7.0
- CUSOLVER: 11.3.2
- CUSPARSE: 11.7.1
- CUPTI: 16.0.0
- NVML: 11.0.0+470.74
- CUDNN: 8.30.2 (for CUDA 11.5.0)
- CUTENSOR: 1.4.0 (for CUDA 11.5.0)

Toolchain:
- Julia: 1.7.2
- LLVM: 12.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

2 devices:
  0: Quadro M6000 24GB (sm_52, 23.898 GiB / 23.902 GiB available)
  1: Quadro M6000 24GB (sm_52, 23.895 GiB / 23.899 GiB available)

**Comment by Marpell** [comment]
Thank you Tim for the fast fix & release, I confirm issue is fixed for me too.
