### ISSUE TITLE
DGX Spark GB10: PkgError: Package CUDA errored during testing

### ISSUE THREAD

**Issue by brian-learns** [JuliaGPU/CUDA.jl#2950]
**Describe the bug**

Tests fail

**To reproduce**

```
(@v1.12) pkg> test CUDA
```

I don't know what a Manifest is, but here are the results of running the tests

https://gist.github.com/brian-learns/bba7ad2f6cb974f41c976a303c61b18d

Here is how I installed this morning.

```
@sparky:~$ sudo snap install julia --classic
@sparky:~$ julia
julia> import Pkg; Pkg.add("CUDA")
julia> using CUDA
julia> CUDA.versioninfo()
CUDA toolchain: 
- runtime 13.0, artifact installation
- driver 580.95.5 for 13.0
- compiler 13.0

CUDA libraries: 
- CUBLAS: 13.1.0
- CURAND: 10.4.0
- CUFFT: 12.0.0
- CUSOLVER: 12.0.4
- CUSPARSE: 12.6.3
- CUPTI: 2025.3.1 (API 13.0.1)
- NVML: 13.0.0+580.95.5

Julia packages: 
- CUDA: 5.9.2
- CUDA_Driver_jll: 13.0.2+0
- CUDA_Compiler_jll: 0.3.0+0
- CUDA_Runtime_jll: 0.19.2+0

Toolchain:
- Julia: 1.12.0
- LLVM: 18.1.7

1 device:
  0: NVIDIA GB10 (sm_121, 109.722 GiB / 119.699 GiB available)
```

**Expected behavior**

passing tests w/o errors

**Version info**

Details on Julia:

```
julia> versioninfo()
Julia Version 1.12.0
Commit b907bd0600f (2025-10-07 15:42 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (aarch64-linux-gnu)
  CPU: 20 × unknown
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, generic)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 20 virtual cores)
```

Details on CUDA:

```
julia> CUDA.versioninfo()
CUDA toolchain: 
- runtime 13.0, artifact installation
- driver 580.95.5 for 13.0
- compiler 13.0

CUDA libraries: 
- CUBLAS: 13.1.0
- CURAND: 10.4.0
- CUFFT: 12.0.0
- CUSOLVER: 12.0.4
- CUSPARSE: 12.6.3
- CUPTI: 2025.3.1 (API 13.0.1)
- NVML: 13.0.0+580.95.5

Julia packages: 
- CUDA: 5.9.2
- CUDA_Driver_jll: 13.0.2+0
- CUDA_Compiler_jll: 0.3.0+0
- CUDA_Runtime_jll: 0.19.2+0

Toolchain:
- Julia: 1.12.0
- LLVM: 18.1.7

1 device:
  0: NVIDIA GB10 (sm_121, 109.839 GiB / 119.699 GiB available)
```

**Additional context**

I was following the directions on the tutorial at https://cuda.juliagpu.org/stable/tutorials/introduction/#Your-first-GPU-computation

**Comment by brian-learns** [comment]
Looks like there are really 2 errors that repeat:

```
ptxas /tmp/jl_IdmXCDgR0l.ptx, line 602; fatal   : Unsupported Function 'cudaDeviceSynchronize' on arch 'sm_90' or higher
```

and 

```
CUDA error: limit is not supported on this architecture (code 215, ERROR_UNSUPPORTED_LIMIT)
```

**Comment by maleadt** [comment]
Both issues are relatively ~harmful~ harmless. The new dynamic parallelism is unsupported, there's other issues for that, but rarely used. The limit is something (probably only a test) to be fixed, but also unlikely to be used in actual user code.

**Comment by brian-learns** [comment]
did you mean *harmful or *harmless?

I was able to complete the Julia CUDA tutorial w/o encountering any errors.

(I upgraded the DGX OS this morning, and it fixed the PyTorch warnings I was getting but these errors look the same)

**Comment by maleadt** [comment]
Sorry, I meant "harmless".

**Comment by habemus-papadum** [comment]
Was going to report the same issue.  In case it helps, here is the full output of Pkg.test("CUDA") on DGX Spark

[CUDA.log](https://github.com/user-attachments/files/23377025/CUDA.log)

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/CUDA.jl/commit/0f67ac3276a8a93fcd850a0dfca9a0aa6c555610
